# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build TRPO-Lab3.sln --no-restore
    - name: Test
      run: dotnet test TRPO-Lab3.sln --no-build --verbosity normal
    - name: Upload ConsoleApp
      uses: actions/upload-artifact@v4
      with:
        path: TRPO-Lab3.ConsoleApp/bin/Debug/net6.0
